# Generated by Django 4.1.7 on 2023-02-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='City', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='number',
            field=models.CharField(default='1', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, default=555555555, max_digits=9),
        ),
        migrations.AddField(
            model_name='profile',
            name='post_code',
            field=models.CharField(default='00-000', max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
